name: Bug Report
description: Something that does not work as intended
title: '[Bug]: '
labels: ['bug']

body:
  - type: textarea
    id: about
    attributes:
      label: About
      description: Describe what happened and what you were expecting to happen
    validations:
      required: true

  - type: textarea
    id: debug
    attributes:
      label: Debug info
      description: Paste in the debug information that can be acquired by going to `Debug > Copy All`

  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: Paste in the logged information found in the browser devtools
