name: Bug Report
description: Something that does not work as intended
title: '[Bug]: '
labels: ['bug']

body:
  - type: textarea
    id: about
    attributes:
      label: About
      description: Describe what happened and what you were expecting to happen
    validations:
      required: true

  - type: textarea
    id: debug
    attributes:
      label: Debug info
      description: Paste in the debug information that can be acquired by going to `Debug > Copy All` (this action may not be available yet for some versions; paste in the log from the console instead)
