title: Stellar
description: 🚀 Documentation for Stellar, a professional blueprint editor for Spaceflight Simulator
twitter_username: TresAbhi_
github_username: TresAbhi

source: docs
url: 'https://tresabhi.github.io/'

remote_theme: svrooij/just-the-docs@relative-everything

permalink: pretty

# base image: https://i.imgur.com/saA9QuC.png
# sizing guide: https://superuser.com/questions/1238552/
logo: 'https://i.imgur.com/saA9QuC.png'
color_scheme: dark
aux_links:
  'GitHub':
    - 'https://github.com/tresabhi/stellar'
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: 'Edit page on GitHub'
gh_edit_repository: 'https://github.com/tresabhi/stellar'
